### ISSUE TITLE
Kestrel does not accept newlines inside STIX patterns

### ISSUE THREAD

**Issue by pcoccoli** [opencybersecurityalliance/kestrel-lang#107]
**Describe the bug**
Kestrel does not accept newlines inside STIX patterns, but accepts newlines elsewhere inside statements.
 
**Details of the bug**
Statement:
```
reg = get process
      from file:///home/pcoccoli/Data/STIX/mitre-brawl.json
      where [process:binary_ref.name = 'reg.exe' AND
             process:parent_ref.binary_ref.name = 'cmd.exe']
```
Error message:
```
kestrel.exceptions.KestrelSyntaxError: [ERROR] KestrelSyntaxError: invalid character "[" at line 3 column 13, expects "STIXPATTERNBODY". rewrite the failed statement.
```
**To Reproduce**
Execute the above statement

**Expected behavior**
The newline should be ignored.  Including newlines in long, complex STIX patterns helps readability.

**Screenshots**
See above

**Environment (please complete the following information):**
- OS: RHEL 8
- Python version: 3.9.2
- Python install environment: Python virtual environment
- STIX-Shifter version: N/A

**Additional context**
N/A

**Comment by subbyte** [comment]
fixed in v1.5
