### ISSUE TITLE
Syntax simplification

### ISSUE THREAD

**Issue by subbyte** [opencybersecurityalliance/kestrel-lang#128]
**Is your feature request related to a problem? Please describe.**
Discussion and planning for syntax revision. Some ideas under discussion:

1. redundant entity type in GET
```
x = GET process FROM datasource WHERE [process:pid = 123]
```
Simplified
```
x = GET process FROM datasource WHERE pid = 123
```

2. redundant entity type in GET from variable
```
w = GET process FROM z WHERE [process:pid = 123]
```
Simplified
```
w = z WHERE pid = 123
```

3. expression
```
<var> [FILTER] [ AGG [ FILTER]] [SORT] [OFFSET] [LIMIT]
```
may use in `DISP` and `COPY`

**Comment by pcoccoli** [comment]
For my "expression" idea (number 3 above), we should be able to use an expression just about anywhere we currently allow a variable.  The exceptions would be in `APPLY` (since this modifies a var in-place) and "parameterized STIX patterns" (although maybe they could actually work here too?).

**Comment by pcoccoli** [comment]
Maybe we should split this into 2 issues: the first is not requiring STIX patterns after `WHERE` but also allowing SQL-like "predicates" (e.g. `pid = 123` instead of `[process:pid = 123]`).
The second issue would be 2/3 above: "expressions"

**Comment by subbyte** [comment]
Agree

**Comment by pcoccoli** [comment]
Resolved in develop
