### ISSUE TITLE
parser upgrade: command input/output

### ISSUE THREAD

**Issue by subbyte** [opencybersecurityalliance/kestrel-lang#13]
the command input output design should obey the table in https://kestrel.readthedocs.io/en/latest/language.html#kestrel-command

`y = DISP x` should not be allowed at parser level.

**Comment by pcoccoli** [comment]
I think I already implemented this:
```
z = DISP procs
[ERROR] VariableNotExist: variable "DISP" does not exist
check the variable used.
```
The error message could be better, but the parser does reject it.
