### ISSUE TITLE
Need versioned documentation

### ISSUE THREAD

**Issue by pcoccoli** [opencybersecurityalliance/kestrel-lang#137]
See https://docs.readthedocs.io/en/stable/versions.html

Since the grammar (and other aspects) can change in each version, we should have versioned documentation.  Otherwise someone using an older version (that may be embedded in another product) may be confused by the latest docs (which are for a newer version).

**Comment by subbyte** [comment]
Enabled via `readthedocs`. Will enable specific version as needed in the future.
