### ISSUE TITLE
stix-shifter max return number of records is too low

### ISSUE THREAD

**Issue by subbyte** [opencybersecurityalliance/kestrel-lang#143]
**Describe the bug**
If a query gets more than 10k returns, then it will fail.

**Details of the bug**
In this case, Kestrel will report error like:
```
[ERROR] DataSourceError: data source internal error: {'error': {'root_cause': [{'type': 'illegal_argument_exception', 'reason': 'Result window is too large, from + size must be less than or equal to: [10000] but was [19999]. See the scroll api for a more efficient way to request large data sets. This limit can be set by changing the [index.max_result_window] index level setting.'}
```
- It is partially caused by stix-shifter that no more than 10k results is allowed by default ([default config](https://github.com/opencybersecurityalliance/stix-shifter/blob/71afea4da5390f183718452b9b3010e530a7cc53/stix_shifter_modules/config.json#L14)).
- And partially by the `elastic_ecs` connector using the basic API that can only retrieve results in the first page of return.

**What to do**
1. Increase the stix-shifter overall limit (config) of data source return, which is simple. An alternative is to set the limit (config) for each connector (or a connector that is in use). The connector config of the limit will override the overall limit.
2. Some connectors, e.g., Elasticsearch, can only retrieve 10k return in its basic API. Thus, the data source API upgrade in the transmission module is required to provide >10k return. Take Elasticsearch as an example, [paging support](https://www.elastic.co/guide/en/elasticsearch/reference/current/paginate-search-results.html) is needed to access infinite return, which requires an API upgrade in the transmission module of the `elastic_ecs` connector.

**Comment by tingdai** [comment]
- Stix-shifter: Expose get_pagesize() API in stix-shifter transmisson module and support pagination using lastsortvalue/metadata in https://github.com/opencybersecurityalliance/stix-shifter/pull/1299
- Kestrel: use pagesize/max_result_window as `retrieval_batch_size`, and extract `lastsort` as `metadata` to support search_after in ElasticSearch https://github.com/opencybersecurityalliance/kestrel-lang/pull/287

**Comment by subbyte** [comment]
Solved in stix-shifter https://github.com/opencybersecurityalliance/stix-shifter/pull/1487

And kestrel-lang>=1.5.12 fetch each page in a separate stix-shifter query. Each page has its own limit, which is not too large. It can be configured in `stixshifter.yaml` from kestrel-lang>=1.6.0

Now this should not be an issue any more.
