### ISSUE TITLE
Error reporting from analytics

### ISSUE THREAD

**Issue by pcoccoli** [opencybersecurityalliance/kestrel-lang#146]
Some analytics (regardless of which interface they use) may call third party APIs, particularly those doing threat intel enrichment.  Sometimes those APIs may fail, either due to authentication issues, temporary network problems, etc.  There is currently no way for the user to be notified of such problems.

There should be some way for analytics to capture such error information and report it back up.  The implementation may differ per analytics interface (e.g. a native python interface where the analytics run under that same python interpreter as the core can probably just raise an exception, while the docker interface may need to write the information to a file).

**Comment by pcoccoli** [comment]
I may be wrong about this; it seems the docker analytics interface captures stderr (and/or stdout) so you *do* see things like python tracebacks:
![image](https://user-images.githubusercontent.com/20825731/156013363-290e5183-acaa-4eca-b90b-d3df01a0f553.png)

**Comment by subbyte** [comment]
yep, we have this supported in both Python and Docker analytics interface.
