### ISSUE TITLE
In-STIX pattern variable auto complete does not work

### ISSUE THREAD

**Issue by subbyte** [opencybersecurityalliance/kestrel-lang#165]
**Describe the bug**
If one tries to auto-complete a variable name in STIX pattern for a parameterized pattern, it does not work.

**Details of the bug**
This is limited to the STIX pattern parser we current use. Need to upgrade parser.

**Comment by pcoccoli** [comment]
Can't we import the STIX grammar into the Kestrel grammar?  I think that way we could make autocomplete work.

**Comment by subbyte** [comment]
We can. Some tests I played with a few days ago: https://github.com/opencybersecurityalliance/kestrel-lang/issues/16
This is a try to import `paramstix.lark` from `firepit` and it works.
Once we do that, another task is to reassemble the STIX pattern from parsed tree when giving it to stix-shifter. I will work with you to see if we can hand the parsed tree to `firepit` to simplify the process when I work on [the parser milestone](https://github.com/opencybersecurityalliance/kestrel-lang/milestone/1).
