### ISSUE TITLE
Simplified WHERE clause

### ISSUE THREAD

**Issue by pcoccoli** [opencybersecurityalliance/kestrel-lang#196]
**Is your feature request related to a problem? Please describe.**
STIX patterns are hard to write.

**Describe the solution you'd like**
Allow SQL-like predicates in place of STIX patterns (i.e. `GET process FROM ... WHERE command_line LIKE '%foo%'` as opposed to `GET process FROM ... WHERE [process:command_line LIKE '%foo%']`
 
**Describe alternatives you've considered**
N/A

**Additional context**
Broken out from #128

**Comment by subbyte** [comment]
implemented in b2b9a0cd70a245bf063d68e9b822b2205bde5770
