### ISSUE TITLE
fast translation deref missed in kestrel 1.6.0 with firepit 2.3.19

### ISSUE THREAD

**Issue by subbyte** [opencybersecurityalliance/kestrel-lang#341]
**Describe the bug**
When fast translation is turned on, there is a chance (non-deterministic) that some reference data is not translated correctly.

**Details of the bug**
- What is the hunt flow/script you are executing?
```
# the data is at https://github.com/opencybersecurityalliance/data-bucket-kestrel/blob/main/elasticsearch/

phishing_candidates = GET process
                      FROM stixshifter://bh22-windows-192.168.56.111
                      WHERE parent_ref.name = 'WinMail.exe' AND binary_ref.name != 'WinMail.exe'
                      START 2022-07-01T00:00:00Z STOP 2022-08-01T00:00:00Z
```
- What is the error message?

There is around 50% chance to get zero return (incorrect) and 50% chance to get 2 entities return (correct). If I turn off fast translation, I always get the correct 2 entities return.

**Dig further**
I checked `local.db` for both the correct run and incorrect run. The 2 entities are shown in the `process` table in both case. However, in the correct run, here's one reference:
```
% sqlite3 local.db 
SQLite version 3.39.5 2022-10-14 20:58:05
Enter ".help" for usage hints.
sqlite> select binary_ref from process;
file--5f6d45a3-4712-5844-a70f-24dbd13a1bb5
file--55268c4b-42b0-5d4e-80bb-bd9e335ae4c2
file--ee48a63e-1ee0-52db-bd9b-d513181c64f3
file--55c4868a-c9fa-57a6-9ccf-0cb72567c9df
file--55c4868a-c9fa-57a6-9ccf-0cb72567c9df
file--55c4868a-c9fa-57a6-9ccf-0cb72567c9df
file--55c4868a-c9fa-57a6-9ccf-0cb72567c9df
file--55c4868a-c9fa-57a6-9ccf-0cb72567c9df
file--053de650-80db-5dac-a38d-359caf64f3d0
file--053de650-80db-5dac-a38d-359caf64f3d0
file--04203b67-28e7-540c-bcb5-4ed82dc98d8c
file--053de650-80db-5dac-a38d-359caf64f3d0
file--9d6a9721-9948-53ff-83f8-3865bc03c727
file--076377b8-55c1-56e2-8d68-f7cb2182efb9
```
And in the incorrect run, here's the same reference value:
```
% sqlite3 local.db 
SQLite version 3.39.5 2022-10-14 20:58:05
Enter ".help" for usage hints.
sqlite> select binary_ref from process;
process_parent_executable
process_executable
process_executable
```
For some reason, the references were not saved correctly, which failed the pattern filter in firepit and returned zero entities.

**Environment (please complete the following information):**
- OS: MacOS
- Python version: 3.9.6
- kestrel: 1.6.0
- STIX-Shifter: 5.3.0
- firepit: 2.3.19

**Comment by pcoccoli** [comment]
This should be fixed with firepit commit 2babde168fd52b21b4938a84a55982818935ba90
https://github.com/opencybersecurityalliance/firepit/releases/tag/v2.3.22
