### ISSUE TITLE
ADDOBSID transformer creates duplicated id field

### ISSUE THREAD

**Issue by subbyte** [opencybersecurityalliance/kestrel-lang#360]
**Describe the bug**

The current `ADDOBSID` transformer implementation creates another field named `id`, which duplicates with the `id` field of any entities. Need to rename the new field as `observation_id`.

And we may need a unit test for `ADDOBSID`.

**Comment by leila-rashidi** [comment]
Hi @subbyte, thanks for creating this issue. I just wanted to mention that the id of the object will be changed to id:1, but it is good to change names. I hope that I can work in this issue later.

**Comment by subbyte** [comment]
`id:1` does not look a good name, and moving `id` to `id:1` sounds confusing. It is better to have another attribute for the observation id.

Thanks for working on it! Feel free to open a PR for this when ready.

**Comment by pcoccoli** [comment]
What about `x_contained_by_ref` since it will contain the ID of another object, the observation that contained it?

**Comment by pcoccoli** [comment]
Should be fixed by https://github.com/opencybersecurityalliance/firepit/releases/tag/v2.3.24
