### ISSUE TITLE
fast translation failed with stix-shifter 5.3.1

### ISSUE THREAD

**Issue by subbyte** [opencybersecurityalliance/kestrel-lang#364]
**Describe the bug**
When fast translation (firepit 2.3.21) is in-use with stix-shifter 5.3.1, the `firepit.aio.ingest.translate()` function failed with:
```
The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

This will fail the unit test `tests/test_stixshifter_translator.py::test_fast_translate`.

To reproduce the error, we may call `firepit.aio.ingest.translate()` upon `SAMPLE_RESULT.data` in `tests/test_stixshifter_translator.py` directly.

**Comment by pcoccoli** [comment]
I believe this is fixed by https://github.com/opencybersecurityalliance/firepit/commit/2babde168fd52b21b4938a84a55982818935ba90
