### ISSUE TITLE
fast-translation group attribute issue with stix-shifter 5.3.1

### ISSUE THREAD

**Issue by subbyte** [opencybersecurityalliance/kestrel-lang#370]
**Describe the bug**
In the current `develop` branch or Kestrel v1.7.0, if we enable stix-shifter 5.3.1 (edit `setup.cfg`) with fast translation (edit `stixshifter.yaml`), one of the unit test will fail:
```
queue = <multiprocessing.queues.Queue object at 0x12742bb20>, translator_cnt = 1

    def read_translated_results(queue: Queue, translator_cnt: int):
        for _ in range(translator_cnt):
            for packet in iter(queue.get, STOP_SIGN):
                if packet.success:
                    yield packet.data
                else:
                    log_msg = f"[worker: {packet.worker}] {packet.log.log}"
                    if packet.log.level == logging.ERROR:
                        _logger.debug(log_msg)
>                       raise DataSourceError(log_msg)
E                       kestrel.exceptions.DataSourceError: [ERROR] DataSourceError: [worker: Translator-4] STIX-shifter fast translation parquet write to disk failed: [ArrowTypeError] ("Expected bytes, got a 'list' object", 'Conversion failed for column event#x-oca-event:category with type object')
E                       please check data source config or test the query manually.

../../../venv/kestrel-dev/lib/python3.9/site-packages/kestrel_datasource_stixshifter/multiproc.py:100: DataSourceError
====================================== short test summary info =======================================
FAILED tests/test_stixshifter_translator.py::test_stixshifter_fast_translate_with_parquet_writing_to_disk - kestrel.exceptions.DataSourceError: [ERROR] DataSourceError: [worker: Translator-4] STIX-shifter ...
==================================== 1 failed, 3 passed in 3.46s =====================================
```

**Details of the bug**
This bug is triggered by:
1. The event section of data in the `tests/test_stixshifter_translator.py`:
```
            "event": {
                "code": 3,
                "provider": "Microsoft-Windows-Sysmon",
                "kind": "event",
                "created": "2021-04-10T05:35:43.069Z",
                "module": "sysmon",
                "action": "Network connection detected (rule: NetworkConnect)",
                "category": ["network"],
                "type": ["connection", "start", "protocol"],
            },
```
2. The latest `to_stix_map` in stix-shfiter 5.3.1 with `group` as follows:
```
    "category": {
      "key": "x-oca-event.category",
      "group": true,
      "object": "event"
    },
    "kind": {
      "key": "x-oca-event.category",
      "group": true,
      "object": "event",
      "transformer": "ValueToList"
    },
    "type": {
      "key": "x-oca-event.category",
      "group": true,
      "object": "event"
    },
```
If we remove `      "group": true,` in `kind`, the error will be gone.

**To Reproduce**
A special thing about debug: usually if someone dynamically edit the stix-shifter mapping, he/she needs to modify `stix_shifter_modules/<CONNECTOR>/configuration/config.json` as mentioned in https://github.com/opencybersecurityalliance/stix-shifter/blob/develop/adapter-guide/custom_mappings.md. However, fast translation load the mapping using the `translation.translate()` function, which load from `stix_shifter_modules/elastic_ecs/stix_translation/json/to_stix_map.json`. So to test a different mapping, one needs to edit the latter JSON file.

**Expected behavior**
No error and the unit test to pass.

**Comment by pcoccoli** [comment]
I think the problem is that in firepit/aio/ingest.py, the `translate` function, we first merge the `group`ed columns, and then run the transformers.  However, each native field has its own transformers, so we should run those first, THEN merge the columns.

**Comment by subbyte** [comment]
Agree. Likely this is the case with `transformers`.

When I edited the test a little to not trigger transformers, it passed successfully:
- In `tests/test_stixshifter_translator.py`: `"kind": "event",` -> `"kind": ["event"],`
- In `stix_shifter_modules/elastic_ecs/stix_translation/json/to_stix_map.json`
  - remove the line `"transformer": "ValueToList"` for `kind`
  - remove the `,` at the end of previous line

Rerun the unit test to pass.
