### ISSUE TITLE
kestrel_datasource_stixshifter doesn't delete searches

### ISSUE THREAD

**Issue by pcoccoli** [opencybersecurityalliance/kestrel-lang#458]
**Describe the bug**
stix-shifter has a "transmit delete" operation (`stix_transmission.DELETE`) but the interface doesn't use it.  On some data sources (e.g. qradar, gcp_chronicle, bigquery) this should result in old searches/search results being orphaned on the data source.

After fetching all results, we should call the delete operation.  Some stix-shifter modules may not implement it, so we need to catch (and ignore or just log) `NotImplementedError`.

**Comment by subbyte** [comment]
https://github.com/opencybersecurityalliance/kestrel-lang/pull/460
