### ISSUE TITLE
kestrel2's SqliteCache should just be SqlCache?

### ISSUE THREAD

**Issue by pcoccoli** [opencybersecurityalliance/kestrel-lang#529]
We have a SqliteCache implemented using SQLAlchemy; the whole point of SQLAlchemy is database abstraction.  We should refactor the class to work with any SQLAlchemy engine/dialect in order to support deployments with no persistent local storage.

See https://github.com/opencybersecurityalliance/kestrel-lang/blob/develop/packages/kestrel_core/src/kestrel/cache/sqlite.py

**Comment by subbyte** [comment]
Yes, good point.

**Comment by subbyte** [comment]
I am editing `cache/sqlite.py`, maybe let me add a commit for this after my current commit.
